In [1]:
[1,2,3,4]

[1, 2, 3, 4]

In [2]:
import array

In [4]:
array.array('i', [1,2,3,4])

array('i', [1, 2, 3, 4])

In [5]:
[1, 'a']

[1, 'a']

In [6]:
array.array('i', [1, 'a'])

TypeError: an integer is required (got type str)

## NUMPY

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
lst = [1,2,3,4]

In [10]:
nplst = np.array(lst)

In [11]:
nplst

array([1, 2, 3, 4])

In [12]:
type(lst)

list

In [13]:
type(nplst)

numpy.ndarray

In [14]:
nplst

array([1, 2, 3, 4])

In [15]:
nplst.dtype

dtype('int64')

In [16]:
nplst.shape

(4,)

In [17]:
nplst.size

4